import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FaFileDownload } from "react-icons/fa";
import Footer from "./components/footer";
import Link from 'next/link';
import Image from 'next/image';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {/* Fixed Navbar Start */}
        <header className="fixed top-0 left-0 right-0 z-50 bg-[#b39ddb] shadow-lg backdrop-blur-sm bg-opacity-95 transition-all duration-300">
          <div className="container mx-auto flex flex-wrap p-4 flex-col md:flex-row items-center">
            <a className="flex title-font font-medium items-center text-black font-bold mb-4 md:mb-0 group transition-all duration-300 hover:scale-105">
              <div className="w-10 h-10 flex items-center justify-center mr-2 rounded-full bg-white border-2 border-black shadow-lg group-hover:shadow-xl transition-all duration-300 group-hover:rotate-12">
                <Image src="/assests/picture/pf.png" alt="Logo" width={32} height={32} className="rounded-full" />
              </div>
              <span className="ml-3 text-xl font-bold text-black">Amio Rashid</span>
            </a>
            <nav className="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center font-bold">
              <Link href="/" className="mr-6 text-black hover:text-yellow-500 transition-all duration-300 hover:scale-110 font-medium relative group">
                Home
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-yellow-300 to-orange-400 group-hover:w-full transition-all duration-300"></span>
              </Link>
              <a href="#About" className="mr-6 text-black hover:text-yellow-500 transition-all duration-300 hover:scale-110 font-medium relative group">
                About
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-yellow-300 to-orange-400 group-hover:w-full transition-all duration-300"></span>
              </a>
              <a href="#Skills" className="mr-6 text-black hover:text-yellow-500 transition-all duration-300 hover:scale-110 font-medium relative group">
                Skills
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-yellow-300 to-orange-400 group-hover:w-full transition-all duration-300"></span>
              </a>
              <a href="#project" className="mr-6 text-black hover:text-yellow-500 transition-all duration-300 hover:scale-110 font-medium relative group">
                Projects
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-yellow-300 to-orange-400 group-hover:w-full transition-all duration-300"></span>
              </a>
              <a href="#Experience" className="mr-6 text-black hover:text-yellow-500 transition-all duration-300 hover:scale-110 font-medium relative group">
                Experience
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-yellow-300 to-orange-400 group-hover:w-full transition-all duration-300"></span>
              </a>
              <a href="#HonorsAndAwards" className="mr-6 text-black hover:text-yellow-500 transition-all duration-300 hover:scale-110 font-medium relative group">
                Honors & Awards
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-yellow-300 to-orange-400 group-hover:w-full transition-all duration-300"></span>
              </a>
              <a href="#Education" className="mr-6 text-black hover:text-yellow-500 transition-all duration-300 hover:scale-110 font-medium relative group">
                Education
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-yellow-300 to-orange-400 group-hover:w-full transition-all duration-300"></span>
              </a>
              <a href="#Contact" className="mr-6 text-black hover:text-yellow-500 transition-all duration-300 hover:scale-110 font-medium relative group">
                Contact
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-gradient-to-r from-yellow-300 to-orange-400 group-hover:w-full transition-all duration-300"></span>
              </a>
            </nav>
            <div className="inline-flex items-center"></div>
            <button className="inline-flex items-center bg-gradient-to-r from-purple-600 via-blue-600 to-indigo-600 hover:from-indigo-600 hover:via-blue-600 hover:to-purple-600 border-0 py-2 px-4 focus:outline-none rounded-full text-white font-medium shadow-lg hover:shadow-xl transition-all duration-300 hover:scale-105 mt-4 md:mt-0 group">
              <a
                href="/assests/cv/Amio_Rashid_CV.pdf"
                download
                className="flex items-center"
              >
                Download CV
                <FaFileDownload className="ml-2 group-hover:animate-bounce" />
              </a>
            </button>
          </div>
        </header>
        {/* Fixed Navbar End */}

        {/* Add padding to account for fixed navbar */}
        <div className="pt-20">
          {children}
        </div>

        <Footer />

      </body>
    </html>
  );
}
